---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  #Install elasticsearch
    # - name: install java 11
    #   shell: apt install default-jre -y
    - name: Download Elasticsearch-sha512
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-amd64.deb.sha512
        dest: /etc

    - name: Download Elasticsearch
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-amd64.deb
        dest: /etc

    - name: Elasticsearch sha512
      shell: shasum -a 512 -c elasticsearch-7.12.0-amd64.deb.sha512
      become: yes
      become_user: root
      args:
        chdir: /etc/

    - name: Install Elasticsearch
      apt:
        deb: /etc/elasticsearch-7.12.0-amd64.deb

    - name: Copying elasticsearch template
      copy: src=template/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

    - name: Start ElasticSearch
      service:
        name: elasticsearch
        state: started
        enabled: yes
        
  #Install kibana
    - name: Download Kibana
      get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-7.12.0-amd64.deb
        dest: /etc
        
    - name: Install Kibana
      apt:
        deb: /etc/kibana-7.12.0-amd64.deb

    - name: Copying kibana template
      copy: src=template/kibana.yml dest=/etc/kibana/kibana.yml

    - name: Start Kibana Service
      service:
        name: kibana
        state: started
        enabled: yes

    - name: Wait for port 5601 to become open on the host
      wait_for:
        port: 5601
        delay: 10

  #Install metricbeat
    - name: Download Metricbeat
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.12.0-amd64.deb
        dest: /etc

    - name: Install Metricbeat
      apt:
        deb: /etc/metricbeat-7.12.0-amd64.deb

    - name: Copying metricbeat template
      copy: src=template/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml

  # start metricbeat
    - name: Permission metricbeat file metricbeat.yml
      file:
        path: /etc/metricbeat/metricbeat.yml 
        owner: root
        group: root

    - name: Permission metricbeat file system.yml
      file:
        path: /etc/metricbeat/modules.d/system.yml
        owner: root
        group: root